[pytest]
addopts = --alluredir=allure-results --screenshot=only-on-failure --clean-alluredir
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: UI functional tests for the frontend
    api: Backend API integration tests
    smoke: Critical path tests for sanity checks
    hybrid: Combined UI and API scenarios
    db: TBD
    # Tags for different sites
    demoblaze: Tests specifically for the Demoblaze store
    reqres: Tests for the ReqRes API service
    # Tags for negative tests
    negative: TBD